Course/course/urls.py
from django.conf.urls import url
from . import views

app_name = 'course'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<course_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<notes_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^notes/(?P<filter_by>[a-zA_Z]+)/$', views.notes, name='notes'),
    url(r'^create_course/$', views.create_course, name='create_course'),
    url(r'^(?P<course_id>[0-9]+)/create_notes/$', views.create_notes, name='create_notes'),
    url(r'^(?P<course_id>[0-9]+)/delete_notes/(?P<notes_id>[0-9]+)/$', views.delete_notes, name='delete_notes'),
    url(r'^(?P<course_id>[0-9]+)/favorite_course/$', views.favorite_course, name='favorite_course'),
    url(r'^(?P<course_id>[0-9]+)/delete_course/$', views.delete_course, name='delete_course'),
]

Course/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^course/', include('course.urls')),
    url(r'^', include('course.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Course/course/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Course(models.Model):
    user = models.ForeignKey(User, default=1)
    author = models.CharField(max_length=250)
    course_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    course_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.course_title + ' - ' + self.author


class Notes(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    chapter_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.chapter_title

Course/course/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Course, Notes


class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ['author', 'course_title', 'genre', 'course_logo']


class NotesForm(forms.ModelForm):

    class Meta:
        model = Notes
        fields = ['chapter_title', 'audio_file']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Course/course/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import CourseForm, NotesForm, UserForm
from .models import Course, Notes

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def create_course(request):
    if not request.user.is_authenticated():
        return render(request, 'course/login.html')
    else:
        form = CourseForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            course = form.save(commit=False)
            course.user = request.user
            course.course_logo = request.FILES['course_logo']
            file_type = course.course_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'course': course,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'course/create_course.html', context)
            course.save()
            return render(request, 'course/detail.html', {'course': course})
        context = {
            "form": form,
        }
        return render(request, 'course/create_course.html', context)


def create_notes(request, course_id):
    form = NotesForm(request.POST or None, request.FILES or None)
    course = get_object_or_404(Course, pk=course_id)
    if form.is_valid():
        courses_notes = course.notes_set.all()
        for s in courses_notes:
            if s.chapter_title == form.cleaned_data.get("chapter_title"):
                context = {
                    'course': course,
                    'form': form,
                    'error_message': 'You already added that notes',
                }
                return render(request, 'course/create_notes.html', context)
        notes = form.save(commit=False)
        notes.course = course
        notes.audio_file = request.FILES['audio_file']
        file_type = notes.audio_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            context = {
                'course': course,
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, or OGG',
            }
            return render(request, 'course/create_notes.html', context)

        notes.save()
        return render(request, 'course/detail.html', {'course': course})
    context = {
        'course': course,
        'form': form,
    }
    return render(request, 'course/create_notes.html', context)


def delete_course(request, course_id):
    course = Course.objects.get(pk=course_id)
    course.delete()
    courses = Course.objects.filter(user=request.user)
    return render(request, 'course/index.html', {'courses': courses})


def delete_notes(request, course_id, notes_id):
    course = get_object_or_404(Course, pk=course_id)
    notes = Notes.objects.get(pk=notes_id)
    notes.delete()
    return render(request, 'course/detail.html', {'course': course})


def detail(request, course_id):
    if not request.user.is_authenticated():
        return render(request, 'course/login.html')
    else:
        user = request.user
        course = get_object_or_404(Course, pk=course_id)
        return render(request, 'course/detail.html', {'course': course, 'user': user})


def favorite(request, notes_id):
    notes = get_object_or_404(Notes, pk=notes_id)
    try:
        if notes.is_favorite:
            notes.is_favorite = False
        else:
            notes.is_favorite = True
        notes.save()
    except (KeyError, Notes.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_course(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    try:
        if course.is_favorite:
            course.is_favorite = False
        else:
            course.is_favorite = True
        course.save()
    except (KeyError, Course.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'course/login.html')
    else:
        courses = Course.objects.filter(user=request.user)
        notes_results = Notes.objects.all()
        query = request.GET.get("q")
        if query:
            courses = courses.filter(
                Q(course_title__icontains=query) |
                Q(author__icontains=query)
            ).distinct()
            notes_results = notes_results.filter(
                Q(chapter_title__icontains=query)
            ).distinct()
            return render(request, 'course/index.html', {
                'courses': courses,
                'notes': notes_results,
            })
        else:
            return render(request, 'course/index.html', {'courses': courses})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'course/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                courses = Course.objects.filter(user=request.user)
                return render(request, 'course/index.html', {'courses': courses})
            else:
                return render(request, 'course/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'course/login.html', {'error_message': 'Invalid login'})
    return render(request, 'course/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                courses = Course.objects.filter(user=request.user)
                return render(request, 'course/index.html', {'courses': courses})
    context = {
        "form": form,
    }
    return render(request, 'course/register.html', context)


def notes(request, filter_by):
    if not request.user.is_authenticated():
        return render(request, 'course/login.html')
    else:
        try:
            notes_ids = []
            for course in Course.objects.filter(user=request.user):
                for notes in course.notes_set.all():
                    notes_ids.append(notes.pk)
            users_notes = Notes.objects.filter(pk__in=notes_ids)
            if filter_by == 'favorites':
                users_notes = users_notes.filter(is_favorite=True)
        except Course.DoesNotExist:
            users_notes = []
        return render(request, 'course/notes.html', {
            'notes_list': users_notes,
            'filter_by': filter_by,
        })

Course/course/templates/course/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Teach Me{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Permanent+marker' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'course/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'course/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'course:index' %}">Teach Me</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block courses_active %}{% endblock %}"><a href="{% url 'course:index' %}"><span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Course List</a></li>
                <li class="{% block notes_active %}{% endblock %}"><a href="{% url 'course:notes' 'all' %}"><span class="glyphicon glyphicon-tag" aria-hidden="true"></span>&nbsp; Notes</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'course:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'course:create_course' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Course
                    </a>
                </li>
                <li>
                    <a href="{% url 'course:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Course/course/templates/course/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Teach Me{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Permanent+marker' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'course/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'course/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'course:index' %}">Teach Me</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'course:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'course:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Course/course/templates/course/create_notes.html
{% extends 'course/base.html' %}
{% block title %}Add a New Notes{% endblock %}
{% block courses_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Course Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'course:detail' course.id %}">
                            {% if course.course_logo %}
                                <img src="{{ course.course_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ course.course_title }} <small>{{ course.genre }}</small></h1>
                    <h2>{{ course.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Notes Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'course:detail' course.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'course:create_notes' course.id %}">Add New Notes</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Notes</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="course" value="{{ course }}">
                        {% include 'course/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

Course/course/templates/course/detail.html
{% extends 'course/base.html' %}
{% block title %}{{ course }}{% endblock %}
{% block courses_active %}active{% endblock %}

{% block body %}
<div class="container-fluid notes-container">

    <div class="row">

        <!-- Left Course Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'course:detail' course.id %}">
                        {% if course.course_logo %}
                            <img src="{{ course.course_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ course.course_title }} <small>{{ course.genre }}</small></h1>
                    <h2>{{ course.author }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Notes Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'course:detail' course.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'course:create_notes' course.id %}">Add New Notes</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Notes</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Chapter Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for notes in course.notes_set.all %}
                            <tr>
                                <td>{{ notes.chapter_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ notes.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'course:favorite' course.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if notes.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'course:delete_notes' course.id notes.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="notes_id" value="{{ notes.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

Course/course/templates/course/index.html
{% extends 'course/base.html' %}
{% block courses_active %}active{% endblock %}

{% block body %}
<div class="courses-container container-fluid">

    <!-- Courses -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Courses</h3>
        </div>
        {% if courses %}
            {% for course in courses %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'course:detail' course.id %}">
                            <img src="{{ course.course_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ course.course_title }}</h2>
                            <h4>{{ course.author }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'course:detail' course.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Course -->
                            <form action="{% url 'course:delete_course' course.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="course_id" value="{{ course.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Course -->
                            <a href="{% url 'course:favorite_course' course.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if course.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'course:create_course' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Course
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are notes -->
    {% if notes %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Notes</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Chapter Title</th>
                                    <th>Author</th>
                                    <th>Audio File</th>
                                    <th>Course</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for note in notes %}
                                    <tr>
                                        <td>{{ note.chapter_title }}</td>
                                        <td>{{ note.course.author }}</td>
                                        <td>
                                            <a target="_blank" href="{{ note.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'course:detail' note.course.id %}">
                                                <img src="{{ note.course.course_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'course:detail' note.course.id %}">{{ note.course.course_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'course:favorite' note.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if note.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

Course/course/templates/course/login.html
{% extends 'course/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'course:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'course:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

Course/course/templates/course/notes.html
{% extends 'course/base.html' %}
{% block title %}All Notes{% endblock %}
{% block notes_active %}active{% endblock %}

{% block body %}
<div class="container-fluid notes-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}
                class="active"{% endif %}><a href="{% url 'course:notes' 'all' %}">
                View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}
                class="active"{% endif %}><a href="{% url 'course:notes' 'favorites' %}">
                Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Chapter Title</th>
                                <th>Author</th>
                                <th>Audio File</th>
                                <th>Course</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for notes in notes_list %}
                                <tr>
                                    <td>{{ notes.chapter_title }}</td>
                                    <td>{{ notes.course.author }}</td>
                                    <td>
                                        <a target="_blank" href="{{ notes.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'course:detail' notes.course.id %}">
                                            <img src="{{ notes.course.course_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'course:detail' notes.course.id %}">{{ notes.course.course_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'course:favorite' notes.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if notes.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}